### ISSUE TITLE
没有‘Templates\trajectory.ogwu’请问可以上传下吗？谢谢。

### ISSUE THREAD

**Issue by XiaoqiWang** [aofenghanyue/EntryGuidance#1]
你好，这个仓库对我帮助很大，非常感谢，但是运行出现了一个bug
origin.py 中 op.load_book(op.path('u') + r'Templates\trajectory.ogwu'报错，可以上传下相应的文件吗？

**Comment by aofenghanyue** [comment]
origin.py模块是调用origin软件（需要另外安装）作图，我事先在origin里将数据的处理保存成.ogwu模板，然后在origin.py中用保存的模板载入仿真结果实现自动绘图，你自己可以做一个.ogwu模板，也可以用我刚刚上传到\graphics的（不知道版本能不能通用）
但整个程序应该是跑不通的(•_•)，这只是个半成品，最新的程序我放在另一台电脑上被删了...正在抢救

**Comment by XiaoqiWang** [comment]
好的，十分感谢你的回复和帮助！
