### ISSUE TITLE
关于制导周期的问题

### ISSUE THREAD

**Issue by Yihan-zz** [aofenghanyue/EntryGuidance#2]
您好，非常感谢您的这个仓库！有个关于制导周期的问题想请教一下，我看代码里并没有设置制导周期，或者说制导周期和积分步长是一致的。但是在实际情况中，应该不可能存在制导周期是0.001s的情况，想问下您是否尝试过设置更大制导周期的实验，以及有没有这方面的经验可以分享？

**Comment by aofenghanyue** [comment]
> 您好，非常感谢您的这个仓库！有个关于制导周期的问题想请教一下，我看代码里并没有设置制导周期，或者说制导周期和积分步长是一致的。但是在实际情况中，应该不可能存在制导周期是0.001s的情况，想问下您是否尝试过设置更大制导周期的实验，以及有没有这方面的经验可以分享？

这个仓库已经好几年没更新了，当初设计时本人不具备工程经验，设计程序时考虑也不够充分，的确没有将仿真周期与制导周期分离开。如果你想采用小步长的仿真（弹体环节，运动学，动力学等），同时采用大步长的制导（或者是GNC)，我可以根据经验来给一点建议，例如，可以在每个仿真周期都判断是否需要重新计算制导指令（比如仿真时间是否整除制导周期，这样做有可能因为浮点数相除导致整除判断不对，那么可以采用计数的方式，比如每过十个仿真周期就触发一次制导指令计算函数），这样就需要制导周期是仿真周期的整数倍。
